### PR TITLE
Update locals.tf

### PR DESCRIPTION
**Pull request by Nb3l77eo**

### CODE REVIEW

**Comment by Nb3l77eo** [comment]
Ran Plan for dir: `terraform` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/Nb3l77eo/testrepo/24/default/terraform/default.tfplan\" -lock=false" in "/root/.atlantis/repos/Nb3l77eo/testrepo/24/default/terraform": exit status 1
╷
│ Error: Invalid index
│ 
│   on main.tf line 14, in resource "yandex_compute_instance" "node1":
│   14:   platform_id = local.node1_conf_instance_platfrom[terraform.workspace]
│     ├────────────────
│     │ local.node1_conf_instance_platfrom is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on main.tf line 15, in resource "yandex_compute_instance" "node1":
│   15:   count = local.node1_instance_count[terraform.workspace]
│     ├────────────────
│     │ local.node1_instance_count is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on main.tf line 18, in resource "yandex_compute_instance" "node1":
│   18:    cores = local.node1_conf_instance_cores[terraform.workspace]
│     ├────────────────
│     │ local.node1_conf_instance_cores is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on main.tf line 19, in resource "yandex_compute_instance" "node1":
│   19:    memory = local.node1_conf_instance_memory[terraform.workspace]
│     ├────────────────
│     │ local.node1_conf_instance_memory is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵

```
</details>

**Comment by Nb3l77eo** [comment]
atlantis plan -d terraform -w stage

**Comment by Nb3l77eo** [comment]
Ran Plan for dir: `terraform` workspace: `stage`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # yandex_compute_instance.node1[0] will be created
+ resource "yandex_compute_instance" "node1" {
      + allow_stopping_for_update = true
      + created_at                = (known after apply)
      + folder_id                 = (known after apply)
      + fqdn                      = (known after apply)
      + hostname                  = "node10.netology.cloud"
      + id                        = (known after apply)
      + metadata                  = {
          + "user-data" = <<-EOT
                #cloud-config
                users:
                  - name: fuser
                    groups: sudo
                    shell: /bin/bash
                    sudo: ['ALL=(ALL) NOPASSWD:ALL']
                    ssh-authorized-keys:
                      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9rackDcwZvm/J+sqLX7/qdZnNmbHenKyMdgPTfdADmzjoGDsWi5pefPg6MC1Ny+cLtp8MFVPrgxinusJNieEW+TWh0KY93c6FgUPkyAJ2uVcUI9B8nMZIjyMM1En7SJAtWZm4x1s8W4lz9+4cQpZ3Yn/nyZP/tR8T3AGD9B94O/t2zKMH0O8XiYqNgrdHkPTvarkLJLLV81Lv4XGLj6BDEjARpfwUPGkOcdzWOVYQCNmAN5dDlIqY4senukzjtKQKD/fUB2ZmqODG/5gnS6IUJNw6v1X0IgFD+fIHefbzgHiI4jgJQQaO2m7L7qsRdbEyFCpDfCiVZ89XAbX67BpvQZRseCVmkcmLAABhPjrFpdxVQfQFsSZMmT6W3hg6ygeHZd9+Hz+OVjtwDxct2yIDR71zRqIALX70YyVEYv8T24ehGyOfhE5xHZkhNwPpeBPI0oRmrdI/lAnBJUvM84KhiB5KFcoYIF2u9xmTGWr68vxBjHuc3AcnQVd0t3FBzKs= root@vagrant
            EOT
        }
      + name                      = "node-0"
      + network_acceleration_type = "standard"
      + platform_id               = "standard-v3"
      + service_account_id        = (known after apply)
      + status                    = (known after apply)
      + zone                      = "ru-central1-a"

      + boot_disk {
          + auto_delete = true
          + device_name = (known after apply)
          + disk_id     = (known after apply)
          + mode        = (known after apply)

          + initialize_params {
              + block_size  = (known after apply)
              + description = (known after apply)
              + image_id    = "fd8anitv6eua45627i0e"
              + name        = "root-node10"
              + size        = 30
              + snapshot_id = (known after apply)
              + type        = "network-nvme"
            }
        }

      + network_interface {
          + index              = (known after apply)
          + ip_address         = (known after apply)
          + ipv4               = true
          + ipv6               = (known after apply)
          + ipv6_address       = (known after apply)
          + mac_address        = (known after apply)
          + nat                = true
          + nat_ip_address     = (known after apply)
          + nat_ip_version     = (known after apply)
          + security_group_ids = (known after apply)
          + subnet_id          = (known after apply)
        }

      + placement_policy {
          + placement_group_id = (known after apply)
        }

      + resources {
          + core_fraction = 100
          + cores         = 2
          + memory        = 2
        }

      + scheduling_policy {
          + preemptible = (known after apply)
        }
    }

  # yandex_compute_instance.node2["app"] will be created
+ resource "yandex_compute_instance" "node2" {
      + created_at                = (known after apply)
      + folder_id                 = (known after apply)
      + fqdn                      = (known after apply)
      + hostname                  = (known after apply)
      + id                        = (known after apply)
      + metadata                  = {
          + "user-data" = <<-EOT
                #cloud-config
                users:
                  - name: fuser
                    groups: sudo
                    shell: /bin/bash
                    sudo: ['ALL=(ALL) NOPASSWD:ALL']
                    ssh-authorized-keys:
                      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9rackDcwZvm/J+sqLX7/qdZnNmbHenKyMdgPTfdADmzjoGDsWi5pefPg6MC1Ny+cLtp8MFVPrgxinusJNieEW+TWh0KY93c6FgUPkyAJ2uVcUI9B8nMZIjyMM1En7SJAtWZm4x1s8W4lz9+4cQpZ3Yn/nyZP/tR8T3AGD9B94O/t2zKMH0O8XiYqNgrdHkPTvarkLJLLV81Lv4XGLj6BDEjARpfwUPGkOcdzWOVYQCNmAN5dDlIqY4senukzjtKQKD/fUB2ZmqODG/5gnS6IUJNw6v1X0IgFD+fIHefbzgHiI4jgJQQaO2m7L7qsRdbEyFCpDfCiVZ89XAbX67BpvQZRseCVmkcmLAABhPjrFpdxVQfQFsSZMmT6W3hg6ygeHZd9+Hz+OVjtwDxct2yIDR71zRqIALX70YyVEYv8T24ehGyOfhE5xHZkhNwPpeBPI0oRmrdI/lAnBJUvM84KhiB5KFcoYIF2u9xmTGWr68vxBjHuc3AcnQVd0t3FBzKs= root@vagrant
            EOT
        }
      + network_acceleration_type = "standard"
      + platform_id               = "standard-v1"
      + service_account_id        = (known after apply)
      + status                    = (known after apply)
      + zone                      = (known after apply)

      + boot_disk {
          + auto_delete = true
          + device_name = (known after apply)
          + disk_id     = (known after apply)
          + mode        = (known after apply)

          + initialize_params {
              + block_size  = (known after apply)
              + description = (known after apply)
              + image_id    = "fd8anitv6eua45627i0e"
              + name        = "root-node1app"
              + size        = 30
              + snapshot_id = (known after apply)
              + type        = "network-nvme"
            }
        }

      + network_interface {
          + index              = (known after apply)
          + ip_address         = (known after apply)
          + ipv4               = true
          + ipv6               = (known after apply)
          + ipv6_address       = (known after apply)
          + mac_address        = (known after apply)
          + nat                = true
          + nat_ip_address     = (known after apply)
          + nat_ip_version     = (known after apply)
          + security_group_ids = (known after apply)
          + subnet_id          = (known after apply)
        }

      + placement_policy {
          + placement_group_id = (known after apply)
        }

      + resources {
          + core_fraction = 100
          + cores         = 4
          + memory        = 4
        }

      + scheduling_policy {
          + preemptible = (known after apply)
        }
    }

  # yandex_compute_instance.node2["db"] will be created
+ resource "yandex_compute_instance" "node2" {
      + created_at                = (known after apply)
      + folder_id                 = (known after apply)
      + fqdn                      = (known after apply)
      + hostname                  = (known after apply)
      + id                        = (known after apply)
      + metadata                  = {
          + "user-data" = <<-EOT
                #cloud-config
                users:
                  - name: fuser
                    groups: sudo
                    shell: /bin/bash
                    sudo: ['ALL=(ALL) NOPASSWD:ALL']
                    ssh-authorized-keys:
                      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9rackDcwZvm/J+sqLX7/qdZnNmbHenKyMdgPTfdADmzjoGDsWi5pefPg6MC1Ny+cLtp8MFVPrgxinusJNieEW+TWh0KY93c6FgUPkyAJ2uVcUI9B8nMZIjyMM1En7SJAtWZm4x1s8W4lz9+4cQpZ3Yn/nyZP/tR8T3AGD9B94O/t2zKMH0O8XiYqNgrdHkPTvarkLJLLV81Lv4XGLj6BDEjARpfwUPGkOcdzWOVYQCNmAN5dDlIqY4senukzjtKQKD/fUB2ZmqODG/5gnS6IUJNw6v1X0IgFD+fIHefbzgHiI4jgJQQaO2m7L7qsRdbEyFCpDfCiVZ89XAbX67BpvQZRseCVmkcmLAABhPjrFpdxVQfQFsSZMmT6W3hg6ygeHZd9+Hz+OVjtwDxct2yIDR71zRqIALX70YyVEYv8T24ehGyOfhE5xHZkhNwPpeBPI0oRmrdI/lAnBJUvM84KhiB5KFcoYIF2u9xmTGWr68vxBjHuc3AcnQVd0t3FBzKs= root@vagrant
            EOT
        }
      + network_acceleration_type = "standard"
      + platform_id               = "standard-v1"
      + service_account_id        = (known after apply)
      + status                    = (known after apply)
      + zone                      = (known after apply)

      + boot_disk {
          + auto_delete = true
          + device_name = (known after apply)
          + disk_id     = (known after apply)
          + mode        = (known after apply)

          + initialize_params {
              + block_size  = (known after apply)
              + description = (known after apply)
              + image_id    = "fd8anitv6eua45627i0e"
              + name        = "root-node1db"
              + size        = 30
              + snapshot_id = (known after apply)
              + type        = "network-nvme"
            }
        }

      + network_interface {
          + index              = (known after apply)
          + ip_address         = (known after apply)
          + ipv4               = true
          + ipv6               = (known after apply)
          + ipv6_address       = (known after apply)
          + mac_address        = (known after apply)
          + nat                = true
          + nat_ip_address     = (known after apply)
          + nat_ip_version     = (known after apply)
          + security_group_ids = (known after apply)
          + subnet_id          = (known after apply)
        }

      + placement_policy {
          + placement_group_id = (known after apply)
        }

      + resources {
          + core_fraction = 100
          + cores         = 4
          + memory        = 8
        }

      + scheduling_policy {
          + preemptible = (known after apply)
        }
    }

  # yandex_vpc_network.default will be created
+ resource "yandex_vpc_network" "default" {
      + created_at                = (known after apply)
      + default_security_group_id = (known after apply)
      + folder_id                 = (known after apply)
      + id                        = (known after apply)
      + labels                    = (known after apply)
      + name                      = "net"
      + subnet_ids                = (known after apply)
    }

  # yandex_vpc_subnet.default will be created
+ resource "yandex_vpc_subnet" "default" {
      + created_at     = (known after apply)
      + folder_id      = (known after apply)
      + id             = (known after apply)
      + labels         = (known after apply)
      + name           = "subnet"
      + network_id     = (known after apply)
      + v4_cidr_blocks = [
          + "192.168.101.0/24",
        ]
      + v6_cidr_blocks = (known after apply)
      + zone           = "ru-central1-a"
    }

Plan: 5 to add, 0 to change, 0 to destroy.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform -w stage`
* :put_litter_in_its_place: To **delete** this plan click [here](https://3e4e-2a01-540-a5be-2c00-765d-70f9-1c19-55ec.eu.ngrok.io/lock?id=Nb3l77eo%252Ftestrepo%252Fterraform%252Fstage)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform -w stage`
</details>
Plan: 5 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by Nb3l77eo** [comment]
atlantis apply -d terraform -w stage

**Comment by Nb3l77eo** [comment]
Ran Apply for dir: `terraform` workspace: `stage`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by mSU7k0N5 — APPROVED** [review]

**Comment by Nb3l77eo** [comment]
atlantis apply -d terraform -w stage

**Comment by Nb3l77eo** [comment]
Ran Apply for dir: `terraform` workspace: `stage`

<details><summary>Show Output</summary>

```diff
try apply

yandex_vpc_network.default: Creating...
yandex_vpc_network.default: Creation complete after 1s [id=enpseb4qoc4ak9gjet8m]
yandex_vpc_subnet.default: Creating...
yandex_vpc_subnet.default: Creation complete after 1s [id=e9bad5fuj1leti2an6lm]
yandex_compute_instance.node2["db"]: Creating...
yandex_compute_instance.node2["app"]: Creating...
yandex_compute_instance.node1[0]: Creating...
yandex_compute_instance.node2["db"]: Still creating... [10s elapsed]
yandex_compute_instance.node2["app"]: Still creating... [10s elapsed]
yandex_compute_instance.node1[0]: Still creating... [10s elapsed]
yandex_compute_instance.node2["app"]: Still creating... [20s elapsed]
yandex_compute_instance.node1[0]: Still creating... [20s elapsed]
yandex_compute_instance.node2["db"]: Still creating... [20s elapsed]
yandex_compute_instance.node1[0]: Creation complete after 21s [id=fhm4lh2jnrcmcpdf7h5l]
yandex_compute_instance.node2["db"]: Creation complete after 23s [id=fhmsqhtokjjd3p8ukpun]
yandex_compute_instance.node2["app"]: Creation complete after 23s [id=fhm9bfknknhtun22h9am]

Apply complete! Resources: 5 added, 0 changed, 0 destroyed.


```
</details>

**Comment by Nb3l77eo** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform` workspace: `stage`

**Pull request closed without merging**
