### PR TITLE
Update locals.tf

### PR DESCRIPTION
**Pull request by Nb3l77eo**

### CODE REVIEW

**Comment by Nb3l77eo** [comment]
Ran Plan for dir: `terraform` workspace: `default`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/Nb3l77eo/testrepo/23/default/terraform/default.tfplan\" -lock=false" in "/root/.atlantis/repos/Nb3l77eo/testrepo/23/default/terraform": exit status 1
╷
│ Error: Invalid index
│ 
│   on main.tf line 14, in resource "yandex_compute_instance" "node1":
│   14:   platform_id = local.node1_conf_instance_platfrom[terraform.workspace]
│     ├────────────────
│     │ local.node1_conf_instance_platfrom is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on main.tf line 15, in resource "yandex_compute_instance" "node1":
│   15:   count = local.node1_instance_count[terraform.workspace]
│     ├────────────────
│     │ local.node1_instance_count is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on main.tf line 18, in resource "yandex_compute_instance" "node1":
│   18:    cores = local.node1_conf_instance_cores[terraform.workspace]
│     ├────────────────
│     │ local.node1_conf_instance_cores is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on main.tf line 19, in resource "yandex_compute_instance" "node1":
│   19:    memory = local.node1_conf_instance_memory[terraform.workspace]
│     ├────────────────
│     │ local.node1_conf_instance_memory is object with 2 attributes
│     │ terraform.workspace is "default"
│ 
│ The given key does not identify an element in this collection value.
╵

```
</details>

**Comment by Nb3l77eo** [comment]
atlantis help

**Comment by Nb3l77eo** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by Nb3l77eo** [comment]
atlantis plan -d . -w staging

**Comment by Nb3l77eo** [comment]
Ran Plan for dir: `.` workspace: `staging`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/Nb3l77eo/testrepo/23/staging/staging.tfplan\" -lock=false" in "/root/.atlantis/repos/Nb3l77eo/testrepo/23/staging": exit status 1
╷
│ Error: No configuration files
│ 
│ Plan requires configuration to be present. Planning without a configuration
│ would mark everything for destruction, which is normally not what is
│ desired. If you would like to destroy everything, run plan with the
│ -destroy option. Otherwise, create a Terraform configuration file (.tf
│ file) and try again.
╵

```

**Comment by Nb3l77eo** [comment]
atlantis plan -w staging

**Comment by Nb3l77eo** [comment]
Ran Plan for dir: `.` workspace: `staging`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/Nb3l77eo/testrepo/23/staging/staging.tfplan\" -lock=false" in "/root/.atlantis/repos/Nb3l77eo/testrepo/23/staging": exit status 1
╷
│ Error: No configuration files
│ 
│ Plan requires configuration to be present. Planning without a configuration
│ would mark everything for destruction, which is normally not what is
│ desired. If you would like to destroy everything, run plan with the
│ -destroy option. Otherwise, create a Terraform configuration file (.tf
│ file) and try again.
╵

```

**Comment by Nb3l77eo** [comment]
atlantis plan -w stage

**Comment by Nb3l77eo** [comment]
Ran Plan for dir: `.` workspace: `stage`

**Plan Error**
```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/Nb3l77eo/testrepo/23/stage/stage.tfplan\" -lock=false" in "/root/.atlantis/repos/Nb3l77eo/testrepo/23/stage": exit status 1
╷
│ Error: No configuration files
│ 
│ Plan requires configuration to be present. Planning without a configuration
│ would mark everything for destruction, which is normally not what is
│ desired. If you would like to destroy everything, run plan with the
│ -destroy option. Otherwise, create a Terraform configuration file (.tf
│ file) and try again.
╵

```

**Comment by Nb3l77eo** [comment]
atlantis plan -d ./terraform -w stage

**Comment by Nb3l77eo** [comment]
Ran Plan for dir: `terraform` workspace: `stage`

**Plan Error**
<details><summary>Show Output</summary>

```
running "/usr/bin/terraform plan -input=false -refresh -out \"/root/.atlantis/repos/Nb3l77eo/testrepo/23/stage/terraform/stage.tfplan\" -lock=false" in "/root/.atlantis/repos/Nb3l77eo/testrepo/23/stage/terraform": exit status 1
╷
│ Error: Missing resource instance key
│ 
│   on output.tf line 10, in output "Zone_node01_yandex_cloud":
│   10:   value = "${yandex_compute_instance.node1.zone}"
│ 
│ Because yandex_compute_instance.node1 has "count" set, its attributes must
│ be accessed on specific instances.
│ 
│ For example, to correlate with indices of a referring resource, use:
│     yandex_compute_instance.node1[count.index]
╵
╷
│ Error: Missing resource instance key
│ 
│   on output.tf line 14, in output "internal_ip_address_node01_yandex_cloud":
│   14:   value = "${yandex_compute_instance.node1.network_interface.0.ip_address}"
│ 
│ Because yandex_compute_instance.node1 has "count" set, its attributes must
│ be accessed on specific instances.
│ 
│ For example, to correlate with indices of a referring resource, use:
│     yandex_compute_instance.node1[count.index]
╵
╷
│ Error: Missing resource instance key
│ 
│   on output.tf line 18, in output "sudnet_id__node01_yandex_cloud":
│   18:   value = "${yandex_compute_instance.node1.network_interface[*].subnet_id}"
│ 
│ Because yandex_compute_instance.node1 has "count" set, its attributes must
│ be accessed on specific instances.
│ 
│ For example, to correlate with indices of a referring resource, use:
│     yandex_compute_instance.node1[count.index]
╵

```
</details>

**Comment by Nb3l77eo** [comment]
atlantis apply -d ./terraform -w stage

**Comment by Nb3l77eo** [comment]
Ran Apply for dir: `terraform` workspace: `stage`

**Apply Failed**: Pull request must be approved by at least one person other than the author before running apply.

**Review by mSU7k0N5 — APPROVED** [review]

**Comment by Nb3l77eo** [comment]
atlantis apply -d ./terraform -w stage

**Comment by Nb3l77eo** [comment]
Ran Apply for dir: `terraform` workspace: `stage`

**Apply Error**
```
no plan found at path "terraform" and workspace "stage"–did you run plan?
try apply

```

**Pull request closed without merging**
